### ISSUE TITLE
Error EJBAccessException processant anotacions de forma múltiple

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/distribucio#307]
S'ha reportat un error processant anotacions de forma múltiple per un error `javax.ejb.EJBAccessException: Caller unauthorized` establint l'idioma de l'usuari:

`2021-03-24 07:49:37,967 ERROR [es.caib.distribucio.war.helper.SessioHelper] (http-10.215.5.163-58080-56) Error establint l'idioma de l'usuari _codi nom: nif_ 
javax.ejb.EJBAccessException: Caller unauthorized
	at org.jboss.ejb3.security.RoleBasedAuthorizationInterceptorv2.invoke(RoleBasedAuthorizationInterceptorv2.java:199)
...
	at com.sun.proxy.$Proxy293.getUsuariActual(Unknown Source)
	at es.caib.distribucio.war.helper.SessioHelper.processarAutenticacio(SessioHelper.java:49)
	at es.caib.distribucio.war.interceptor.SessioInterceptor.preHandle(SessioInterceptor.java:32)
...`

S'ha d'investigar i evitar aquest tipus d'errors.

**Comment by bgual-dgtic** [comment]
L'error persisteix.
Adjunto logs d'avui
http://tn.caib.es/2phCViL55RMl

**Comment by bgual-dgtic** [comment]
A més de marcar com a processades també es dóna al marcar múltiples per a enviar per correu.
