### ISSUE TITLE
Intentar desbloquejar un annex PDF protegit sense firma abans de firmar-lo en servidor

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/distribucio#671]
Si tenim qualque fitxer PDF bloquejat sense firma, l'acció de firma en servidor  hauria d'intentar desbloquejar-lo prèviament.

Actualment surt aquest error:

```
es.caib.distribucio.core.api.exception.SistemaExternException: Error amb el sistema extern null: No s'ha pogut signar el document.: Error amb el sistema extern null: Error durant la realització de les firmes: Error firmant document 1descarga.pdf (0)[java.lang.Exception]:Error durant la firma: El fichero PDF se encuentra protegido. No es posible realizar la operación.
java.lang.Exception: Error durant la firma: El fichero PDF se encuentra protegido. No es posible realizar la operación.
	at org.fundaciobit.plugins.signatureserver.afirmaserver.AfirmaServerSignatureServerPlugin.signDocuments(AfirmaServerSignatureServerPlugin.java:781)
	at es.caib.portafib.logic.passarela.PassarelaDeFirmaEnServidorEJB.signDocuments(PassarelaDeFirmaEnServidorEJB.java:181)
	at sun.reflect.GeneratedMethodAccessor669.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.aop.joinpoint.MethodInvocation.invokeTarget(MethodInvocation.java:122)
	at org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:111)
	at org.jboss.ejb3.interceptors.container.ContainerMethodInvocationWrapper.invokeNext(ContainerMethodInvocationWrapper.java:72)
	at org.jboss.ejb3.interceptors.aop.InvocationContextInterceptor$InvocationContext.proceed(InvocationContextInterceptor.java:138)
	at es.caib.portafib.ejb.interceptors.LogInterceptor.interceptMethod(LogInterceptor.java:29)
	at sun.reflect.GeneratedMethodAccessor488.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.ejb3.interceptors.aop.EJB3InterceptorInterceptor.invoke(EJB3InterceptorInterceptor.java:83)
	at org.jboss.ejb3.interceptors.aop.EJB3InterceptorInterceptor.invoke(EJB3InterceptorInterceptor.java:70)
	at org.jboss.ejb3.interceptors.container.ContainerMethodInvocationWrapper.invokeNext(ContainerMethodInvocationWrapper.java:62)
	at org...
```

**Comment by acuevas-dgtic** [comment]
Relacionada: https://github.com/GovernIB/ripea/issues/1271
