### ISSUE TITLE
Error de validació: Un document que no te el format PDF (xsig) no pot tenir una firma de tipus PADES

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/distribucio#676]
Intentar corregir aquest error

```
es.caib.plugins.arxiu.api.ArxiuValidacioException: Error de validació: Un document que no te el format PDF (xsig) no pot tenir una firma de tipus PADES
	at es.caib.plugins.arxiu.caib.ArxiuPluginCaib.comprovarFirma(ArxiuPluginCaib.java:1779)
	at es.caib.plugins.arxiu.caib.ArxiuPluginCaib.documentCrear(ArxiuPluginCaib.java:654)
	at es.caib.distribucio.plugin.caib.arxiu.distribucio.DistribucioPluginArxiuImpl.arxiuDocumentAnnexCrearActualizar(DistribucioPluginArxiuImpl.java:619)
	at es.caib.distribucio.plugin.caib.arxiu.distribucio.DistribucioPluginArxiuImpl.saveAnnexAsDocumentInArxiu(DistribucioPluginArxiuImpl.java:351)
	at es.caib.distribucio.core.helper.PluginHelper.saveAnnexAsDocumentInArxiu(PluginHelper.java:173)
	at es.caib.distribucio.core.helper.RegistreHelper.crearAnnexInArxiu(RegistreHelper.java:2274)
	at es.caib.distribucio.core.helper.RegistreHelper$$FastClassBySpringCGLIB$$29e8d8d4.invoke()
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:700)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:633)
	at es.caib.distribucio.core.helper.RegistreHelper$$EnhancerBySpringCGLIB$$5c80e922.crearAnnexInArxiu()
	at es.caib.distribucio.core.helper.RegistreHelper.createRegistreAndAnnexosInArxiu(RegistreHelper.java:810)
	at es...
```

**Comment by josepg-limit** [comment]
No es pot reproduir, es procedeix a tancar la issue.
